name: Deploy IngredientsCatalog

on:
  workflow_dispatch:
    inputs:
      environment_name:
        required: true
        type: string
      version:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment_name }}
    concurrency:
      group: ingredients-catalog-${{ inputs.environment_name }}
      cancel-in-progress: false

    steps:
      - uses: actions/checkout@v4
      - run: echo "TODO explicit catalog DB migration"
      - run: echo "TODO deploy IngredientsCatalog ${{ inputs.version }}"
